Models/Banner.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ASPNetCoreRazorPage_TicketMovie.Models
 {
    [Table("Banner")]
    public class Banner : ModelBase
    {
        [Key]
        public int BAN_ID { get; set; }
        public string? Image { get; set; }
        public string? Name  { get; set; }
    }
 }

Models/Category.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ASPNetCoreRazorPage_TicketMovie.Models
 {
    [Table("Category")]
    public class Category : ModelBase
    {
        [Key]
        public int CAT_ID { get; set; }
        public string? Type  { get; set; }
        public int Age { get; set; }
        public ICollection<Movie>? Movies { get; set; }
    }
 }

Models/Cinema.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ASPNetCoreRazorPage_TicketMovie.Models
 {
    [Table("Cinema")]
    public class Cinema : ModelBase
    {
        [Key]
        public int? CIN_ID { get; set; }
        public string? Name { get; set; }
        public string? Email { get; set; }
        public string? Location { get; set; } 
        public string? Phone { get; set; } 
        public ICollection<Room>? Rooms { get; set; }
    }
 }

Models/MovieDetail.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ASPNetCoreRazorPage_TicketMovie.Models
 {
    [Table("MovieDetail")]
    public class MovieDetail : ModelBase
    {
        [Key]
        public int MOVDT_ID { get; set; }
        public int MOV_ID { get; set; }
        public string? Director  { get; set; }
        public string? Actor { get; set; } 
        public string? Description { get; set; } 
        public string? Type { get; set; } 
        public string? Country { get; set; }
        [ForeignKey("MOV_ID")]
        public Movie? Movie { get; set; }
    }
 }

Models/Payment.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ASPNetCoreRazorPage_TicketMovie.Models
 {
    [Table("Payment")]
    public class Payment : ModelBase
    {
        [Key]
        public int PAY_ID { get; set; }
        public string Code { get; set; } = Guid.NewGuid().ToString("N").Substring(0, 6);
        public string UserId { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public int Price { get; set; }
        public int Discount { get; set; }
        public int Total { get; set; }
        public ICollection<SeatSold>? SeatSolds { get; set; }
    }       
}

Models/Review.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ASPNetCoreRazorPage_TicketMovie.Models
 {
    [Table("Review")]
    public class Review : ModelBase
    {
        [Key]
        public int REV_ID { get; set; }
        public int MOV_ID { get; set; }
        public string? UserID { get; set; }
        public string? UserName { get; set; }
        public string? Comment { get; set; }
        public int Rating { get; set; }
        [ForeignKey("MOV_ID")]
        public Movie? Movie { get; set; }
    }
}

Models/Room.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ASPNetCoreRazorPage_TicketMovie.Models
 {
    [Table("Room")]
    public class Room : ModelBase
    {
        [Key]
         public int ROO_ID { get; set; }
        public string? Name { get; set; }
        public int CIN_ID { get; set; }
        [ForeignKey("CIN_ID")]
        public Cinema? Cinema { get; set; }
        public ICollection<Seat>? Seats { get; set; }
        public ICollection<Screen>? Screens { get; set; }
    }
}

Models/Screen.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ASPNetCoreRazorPage_TicketMovie.Models
{
    [Table("Screen")]
    public class Screen : ModelBase
    {
        [Key]
        public int SCR_ID { get; set; }
        public int MOV_ID { get; set; }
        public int ROO_ID { get; set; }
        public string? Name { get; set; }
        public DateTime TimeStart { get; set; }
        public DateTime TimeEnd { get; set; } 
        public DateTime? Date { get; set; }
        [ForeignKey("ROO_ID")]
        public Room? Room { get; set; }
        [ForeignKey("MOV_ID")]
        public Movie? Movie { get; set; }
    }
}

Models/Seat.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ASPNetCoreRazorPage_TicketMovie.Models
 {
    [Table("Seat")]
    public class Seat : ModelBase
    {
        [Key]
        public int SEA_ID { get; set; }
        public int ROO_ID { get; set; }
        public string? Name { get; set; }
        public string? Type { get; set; }  
        public int Price { get; set; }
        [ForeignKey("ROO_ID")]
        public Room? Room { get; set; }
        public ICollection<SeatSold>? SeatSolds { get; set; }
    }
}

Pages/Admin/Banner.cshtml.cs
using ASPNetCoreRazorPage_TicketMovie.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace ASPNetCoreRazorPage_TicketMovie.Pages.Admin
{
    [Authorize(Roles = "admin")]
    public class BannerModel : PageModel
    {
        private readonly AppDataContext _context;
        public Banner? Banner { get; set; }
        public IList<Banner>? Banners { get; set; }

        [BindProperty]
        public Banner Ban { get; set; }

        [BindProperty]
        public Input? Images { get; set; }

        [BindProperty] 
        public int ID { get; set; }

        /// <summary>
        ///     Constructor function
        /// </summary>
        public BannerModel(AppDataContext context)
        {
            _context = context;
            Ban = new Banner();
        }

        /// <summary>
        ///     Start view for page
        /// </summary>
        public async Task OnGetAsync()
        {
            Banners = await _context.Banners.AsNoTracking().ToListAsync();
        }

        /// <summary>
        /// Add Banner
        /// </summary>
        public async Task<IActionResult> OnPostAddAsync()
        {
            if (Images!.Image != null)
            {
                var filename = Path.GetFileName(Images.Image.FileName);
                var filepath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/banners", filename);
                using (var stream = new FileStream(filepath, FileMode.Create))
                {
                    Images.Image.CopyTo(stream);
                }
                var banner = new Banner
                {
                    Name = Ban.Name,
                    Image = filename
                };
                await _context.Banners.AddAsync(banner);
                await _context.SaveChangesAsync();
                return RedirectToPage();
            }
            else
            {
                return BadRequest();
            }
        }

        /// <summary>
        ///     Edit Banner
        /// </summary>
        public async Task<IActionResult> OnPostEditAsync()
        {
            Banner = await _context.Banners.FirstOrDefaultAsync(x => x.BAN_ID == Ban.BAN_ID);
            if (Banner != null)
            {
                if (Images?.Image == null)
                {
                    Banner.Name = Ban.Name;
                    Banner.UpdatedDate = DateTime.Now;
                    _context.Banners.Update(Banner);
                    await _context.SaveChangesAsync();
                    return RedirectToPage();
                }
                else
                {
                    //DELETE IMAGE
                    var imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/banners", Banner.Image!);
                    if (System.IO.File.Exists(imagePath))
                    {
                        System.IO.File.Delete(imagePath);
                    }
                    //UPDATE IMAGE
                    var filename = Path.GetFileName(Images.Image.FileName);
                    var filepath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/banners", filename);
                    using (var stream = new FileStream(filepath, FileMode.Create))
                    {
                        Images.Image.CopyTo(stream);
                    }
                    Banner.Name = Ban.Name;
                    Banner.Image = filename;
                    Banner.UpdatedDate = DateTime.Now;
                    _context.Banners.Update(Banner);
                    await _context.SaveChangesAsync();
                    return RedirectToPage();
                }
            }
            return BadRequest();
        }

        /// <summary>
        ///     Delete Banner
        /// </summary>
        public async Task<IActionResult> OnPostDeleteAsync()
        {
            Banner = await _context.Banners.FirstOrDefaultAsync(x => x.BAN_ID == ID);
            if(Banner != null)
            {
                var imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/banners", Banner.Image!);
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
                _context.Banners.Remove(Banner);
                await _context.SaveChangesAsync();
                return RedirectToPage();
            }    
            return NotFound();
        }
    }
}

Pages/Admin/Category.cshtml.cs
using ASPNetCoreRazorPage_TicketMovie.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using static System.Net.Mime.MediaTypeNames;

namespace ASPNetCoreRazorPage_TicketMovie.Pages.Admin
{
    [Authorize(Roles = "admin")]
    public class CategoryModel : PageModel
    {
        private readonly AppDataContext _context;
        public IList<Category>? Categories { get; set; }
        [BindProperty]
        public Category? Category { get; set; }
        [BindProperty]
        public int ID { get; set; }
        public CategoryModel(AppDataContext context)
        {
            _context = context;
            Categories = new List<Category>();
        }
        public async Task OnGetAsync()
        {
            Categories = await _context.Categories.AsNoTracking().ToListAsync();
        }
        /// <summary>
        /// Add
        /// </summary>
        public async Task<IActionResult> OnPostAddAsync()
        {
            var cat = new Category
            {
                Type = Category!.Type,
                Age = Category.Age,
                CreatedDate = DateTime.Now,
            };
            await _context.Categories.AddAsync(cat);
            await _context.SaveChangesAsync();
            return RedirectToPage();
        }
        /// <summary>
        ///     Edit 
        /// </summary>
        public async Task<IActionResult> OnPostEditAsync()
        {
            var category = await _context.Categories.FirstOrDefaultAsync(x => x.CAT_ID == Category!.CAT_ID);
            if (category != null)
            {
                category.Type = Category!.Type;
                category.Age = Category.Age;
                category.UpdatedDate = DateTime.Now;
                _context.Update(category);
                await _context.SaveChangesAsync();
                return RedirectToPage();
            }
            return BadRequest();
        }
        /// <summary>
        ///     Delete
        /// </summary>
        public async Task<IActionResult> OnPostDeleteAsync()
        {
            Category = await _context.Categories.FirstOrDefaultAsync(x => x.CAT_ID == ID);
            if (Category != null)
            {
                _context.Categories.Remove(Category);
                await _context.SaveChangesAsync();
                return RedirectToPage();
            }
            return NotFound();
        }
    }
}

Pages/Admin/Cinema.cshtml.cs
using ASPNetCoreRazorPage_TicketMovie.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ASPNetCoreRazorPage_TicketMovie.Pages.Admin
{
    [Authorize(Roles = "admin")]
    public class CinemaModel : PageModel
    {
        private readonly AppDataContext _context;
        public IList<Cinema>? Cinemas { get; set; }
        public CinemaModel(AppDataContext context) { 
            _context = context;
            Cinemas = new List<Cinema>();
        }
        public async Task OnGetAsync()
        {
            Cinemas = await _context.Cinemas.AsNoTracking().ToListAsync();
        }
    }
}

Pages/Admin/Index.cshtml.cs
using ASPNetCoreRazorPage_TicketMovie.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASPNetCoreRazorPage_TicketMovie.Pages.Admin
{
    [Authorize(Roles = "admin")]
    public class IndexModel : PageModel
    {
        private readonly UserManager<UserOA> _userManager;
        private readonly AppDataContext _context;

        public IndexModel(AppDataContext context, UserManager<UserOA> userManager) {
            _context = context;
            _userManager = userManager;
        }
        public async Task OnGetAsync()
        {
            var user = await _userManager.GetUserAsync(User);
        }
    }
}

Pages/Admin/Movie.cshtml.cs
using ASPNetCoreRazorPage_TicketMovie.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ASPNetCoreRazorPage_TicketMovie.Pages.Admin
{
    [Authorize(Roles = "admin")]
    public class MovieModel : PageModel
    {
        private readonly AppDataContext _context;
        public IList<Movie>? Movies { get; set; }
        public MovieModel(AppDataContext context)
        {
            _context = context;
            Movies = new List<Movie>();
        }
        public async Task OnGetAsync()
        {
            Movies = await _context.Movies.Include(x => x.Category).AsNoTracking().ToListAsync();
        }
    }
}

Pages/Admin/MovieDetail.cshtml.cs
using ASPNetCoreRazorPage_TicketMovie.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ASPNetCoreRazorPage_TicketMovie.Pages.Admin
{
    public class MovieDetailModel : PageModel
    {
        private readonly AppDataContext _context;
        public IList<MovieDetail> MoveDetails { get; set; }
        public MovieDetailModel(AppDataContext context)
        {
            _context = context;
            MoveDetails = new List<MovieDetail>();
        }
        public async Task OnGetAsync()
        {
            MoveDetails = await _context.MovieDetails.AsNoTracking().ToListAsync();
        }
    }
}

Pages/Admin/Payment.cshtml.cs
using ASPNetCoreRazorPage_TicketMovie.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ASPNetCoreRazorPage_TicketMovie.Pages.Admin
{
    [Authorize(Roles = "admin")]
    public class PaymentModel : PageModel
    {
        private readonly AppDataContext _context;
        public IList<Payment> Payments { get; set; }
        public PaymentModel(AppDataContext context)
        {
            _context = context;
            Payments = new List<Payment>();
        }
        public async Task OnGetAsync()
        {
            Payments = await _context.Payments.Include(x => x.SeatSolds).AsNoTracking().ToListAsync();
        }
    }
}

Pages/Admin/Review.cshtml.cs
using ASPNetCoreRazorPage_TicketMovie.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ASPNetCoreRazorPage_TicketMovie.Pages.Admin
{
    [Authorize(Roles = "admin")]
    public class ReviewModel : PageModel
    {
        private readonly AppDataContext _context;
        public IList<Review> Reviews { get; set; }
        public ReviewModel(AppDataContext context)
        {
            _context = context;
            Reviews = new List<Review>();
        }
        public async Task OnGetAsync()
        {
            Reviews = await _context.Reviews.Include(x => x.Movie).AsNoTracking().ToListAsync();
        }
    }
}

Pages/Admin/Room.cshtml.cs
using ASPNetCoreRazorPage_TicketMovie.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ASPNetCoreRazorPage_TicketMovie.Pages.Admin
{
    [Authorize(Roles = "admin")]
    public class RoomModel : PageModel
    {
        private readonly AppDataContext _context;
        public  IList<Room> Rooms { get; set; }
        public RoomModel(AppDataContext context)
        {
            _context = context;
            Rooms = new List<Room>();
        }
        public async Task OnGetAsync()
        {
            Rooms =await _context.Rooms
                .Include(x => x.Cinema)
                .AsNoTracking()
                .ToListAsync();
        }
    }
}

Pages/Admin/Banner.cshtml
@page
@model ASPNetCoreRazorPage_TicketMovie.Pages.Admin.BannerModel
@{
}
<partial name="/Pages/Admin/Shared/_AddPartial.cshtml" />
<div class="container-fluid">
    <table id="example" class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Image</th>
                <th>Name</th>
                <th>CreateDate</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody id="tbody">
            @if(Model.Banners != null && Model.Banners.Any())
            {
                foreach(var bans in Model.Banners){
                   <tr data-id="@bans.BAN_ID">
                       <td>@bans.BAN_ID</td>
                       <td>@bans.Image</td>
                       <td data-name="@bans.BAN_ID">@bans.Name</td>
                       <td>@bans.CreatedDate</td>
                       <td>
                            <button type="button" data-group="edit" data-type="ban" data-id="@bans.BAN_ID"><i class="ti ti-edit"></i></button>
                            <button type="button" onclick="Delete(@bans.BAN_ID)"><i class="ti ti-trash"></i></button>
                       </td>
                   </tr>
                }
            }
            else
            {
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td colspan="5" class="text-center">Have no data</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<partial name="/Pages/Admin/Shared/_DeletesPartial.cshtml" />
@section Banner {
    active 
}
@section Add {
    <div id="Add" class="fixed-top top-100 container">
        <div class="row justify-content-center">
            <div class="col-auto p-5 shadow-lg bg-light text-center rounded-bottom d-flex flex-column">
                <p class="mb-4 bg-light text-dark p-3 rounded-top">Add Banner</p>
                <form method="post" asp-page-handler="Add" enctype="multipart/form-data">
                    <div class="row mb-3">
                        <label asp-for="Images!.Image" class="col-4 text-end">Image:</label>
                        <input asp-for="Images!.Image" type="file" class="col-6 text-start" accept=".jpg, .jpeg, .png" required /> <br />
                        <span asp-validation-for="Images!.Image" class="text-danger"></span>
                    </div>
                    <div class="row mb-3">
                        <label asp-for="Ban.Name" class="col-4 text-end">Name:</label>
                        <input asp-for="Ban.Name" type="text" class="col-6 text-start" required /><br />
                        <span asp-validation-for="Ban.Name" class="text-danger"></span>
                    </div>
                    <div>
                        <button id="btnAdd" type="submit" class="btn btn-primary me-2">Add</button>
                        <button type="button" onclick="Add()" class="btn btn-danger">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}
@section Edit
{
    <div id="Edit" class="fixed-top top-100 container">
        <div class="row justify-content-center">
            <div class="col-auto p-5 shadow-lg bg-light text-center rounded-bottom d-flex flex-column">
                <p class="mb-4 bg-light text-dark p-3 rounded-top">Edit Banner</p>
                <form method="post" asp-page-handler="Edit" enctype="multipart/form-data">
                    <input asp-for="Ban.BAN_ID" id="ID" type="text" class="col-6 text-start" hidden/><br />
                    <div class="row mb-3">
                        <label asp-for="Images!.Image" class="col-4 text-end">Image:</label>
                        <input asp-for="Images!.Image" id="Image" type="file" class="col-6 text-start" accept=".jpg, .jpeg, .png"/> <br />
                        <span asp-validation-for="Images!.Image" class="text-danger"></span>
                    </div>
                    <div class="row mb-3">
                        <label asp-for="Ban.Name" class="col-4 text-end">Name:</label>
                        <input asp-for="Ban.Name" id="Name" type="text" class="col-6 text-start" required /><br />
                        <span asp-validation-for="Ban.Name" class="text-danger"></span>
                    </div>
                    <div>
                        <button id="btnAdd" type="submit" class="btn btn-primary me-2">Save</button>
                        <button type="button" onclick="Edit()" class="btn btn-danger">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}

Pages/Admin/Category.cshtml
@page
@model ASPNetCoreRazorPage_TicketMovie.Pages.Admin.CategoryModel
@{
}
<partial name="/Pages/Admin/Shared/_AddPartial.cshtml" />
<div class="container-fluid">
    <table id="example" class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Type</th>
                <th>Age</th>
                <th>CreateDate</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @if(Model.Categories != null && Model.Categories.Any()){
                foreach(var cats in Model.Categories){
                    <tr data-id="@cats.CAT_ID">
                        <td>@cats.CAT_ID</td>
                        <td data-type="@cats.CAT_ID">@cats.Type</td>
                        <td data-age="@cats.CAT_ID">@cats.Age</td>
                        <td>@cats.CreatedDate</td>
                        <td>
                            <button type="button" data-group="edit" data-type="cate" data-id="@cats.CAT_ID"><i class="ti ti-edit"></i></button>
                            <button type="button" onclick="Delete(@cats.CAT_ID)"><i class="ti ti-trash"></i></button>
                        </td>

                    </tr>
                }
            }else{
                <tr>
                    <td colspan="5" class="text-center">Have no data</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<partial name="/Pages/Admin/Shared/_DeletesPartial.cshtml" />
@section Category {
    active
}
@section Add
{
    <div id="Add" class="fixed-top top-100 container">
        <div class="row justify-content-center">
            <div class="col-auto p-5 shadow-lg bg-light text-center rounded-bottom d-flex flex-column">
                <p class="mb-4 bg-light text-dark p-3 rounded-top">Add Category</p>
                <form method="post" asp-page-handler="Add">
                    <div class="row mb-3">
                        <label asp-for="Category!.Type" class="col-4 text-end">Type:</label>
                        <input asp-for="Category!.Type" type="text" class="col-6 text-start" required /><br />
                        <span asp-validation-for="Category!.Type" class="text-danger"></span>
                    </div>
                    <div class="row mb-3">
                        <label asp-for="Category!.Age" class="col-4 text-end">Age:</label>
                        <input asp-for="Category!.Age" type="number" class="col-6 text-start" required /><br />
                        <span asp-validation-for="Category!.Age" class="text-danger"></span>
                    </div>
                    <div>
                        <button id="btnAdd" type="submit" class="btn btn-primary me-2">Add</button>
                        <button type="button" onclick="Add()" class="btn btn-danger">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}
@section Edit
{
    <div id="Edit" class="fixed-top top-100 container">
        <div class="row justify-content-center">
            <div class="col-auto p-5 shadow-lg bg-light text-center rounded-bottom d-flex flex-column">
                <p class="mb-4 bg-light text-dark p-3 rounded-top">Edit Banner</p>
                <form method="post" asp-page-handler="Edit" enctype="multipart/form-data">
                    <input asp-for="Category!.CAT_ID" id="ID" type="text" class="col-6 text-start" required hidden/><br />
                    <div class="row mb-3">
                        <label asp-for="Category!.Type" class="col-4 text-end">Type:</label>
                        <input asp-for="Category!.Type" id="Type" type="text" class="col-6 text-start" required /><br />
                        <span asp-validation-for="Category!.Type" class="text-danger"></span>
                    </div>
                    <div class="row mb-3">
                        <label asp-for="Category!.Age" class="col-4 text-end">Age:</label>
                        <input asp-for="Category!.Age" id="Age" type="number" class="col-6 text-start" required /><br />
                        <span asp-validation-for="Category!.Age" class="text-danger"></span>
                    </div>
                    <div>
                        <button id="btnAdd" type="submit" class="btn btn-primary me-2">Save</button>
                        <button type="button" onclick="Edit()" class="btn btn-danger">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}

Pages/Admin/Cinema.cshtml
@page
@model ASPNetCoreRazorPage_TicketMovie.Pages.Admin.CinemaModel
@{
}
<partial name="/Pages/Admin/Shared/_AddPartial.cshtml" />
<div class="container-fluid">
    <table id="example" class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Location</th>
                <th>Phone</th>
                <th>CreateDate</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @if(Model.Cinemas != null && Model.Cinemas.Any()){
                foreach(var cins in Model.Cinemas){
                    <tr data-id="@cins.CIN_ID">
                        <td>@cins.CIN_ID</td>
                        <td>@cins.Name</td>
                        <td>@cins.Email</td>
                        <td>@cins.Location</td>
                        <td>@cins.Phone</td>
                        <td>@cins.CreatedDate</td>
                        <td>
                            <button type="button"><i class="ti ti-edit"></i></button>
                            <button type="button" onclick="Delete(@cins.CIN_ID)"><i class="ti ti-trash"></i></button>
                        </td>

                    </tr>
                }
            }else{
                <tr>
                    <td colspan="7" class="text-center">Have no data</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<partial name="/Pages/Admin/Shared/_DeletesPartial.cshtml" />
@section Cinema {
    active
}
@section Add
{

}
@section Edit
{

}

Pages/Admin/Test.cshtml
 @page
@model ASPNetCoreRazorPage_TicketMovie.Pages.Admin.TestModel
@{
}
<p>
    @Model.TransactionDetails
</p>